### ISSUE TITLE
hosts and services create in wrong config dir in Ubuntu

### ISSUE THREAD

**Issue by jskarpe** [example42/puppet-nagios#41]
In Ubuntu 14.04, the storeconfigs for hosts and services are created in /etc/nagios/auto.d while they should be created in /etc/nagios3 (which is the correct config dir for Nagios under Ubuntu)

The following folders are created correctly:

commands  extra  manual  settings

**Comment by lmorival** [comment]
Hi, i'm new in puppet. I install nagios-puppet(example42) module everything is good. It monitored the basic services for my nagios host. BUT there is one problem i cannot monitor other hosts with the module.

How i can monitor other hosts with the module?
