### ISSUE TITLE
New installation

### ISSUE THREAD

**Issue by SergiuCip** [example42/puppet-nagios#44]
Hi there,

I am using your puppet module in order to install nagios on 2 servers located in different datacenters. The first nagios installation went smooth and everything it is running perfectly. However, for the 2nd nagios installation after I had to chmod for the nagios.cmd all the hosts appears as down including the localhost. 

I have ran the commands as root and as the nagios user, from the command line and they return ok. I have also chmod for all the plugins as the error i am getting it says: (Return code of 127 is out of bounds - plugin may be missing).

Do you have any ideas why has this happen?

Thank you,

Kind regards,
Cip

**Comment by alvagante** [comment]
Actually not,
some more information would help (output of facter, puppet code used, output of the puppet run...)
